### ISSUE TITLE
Sabes que sólo puedes participar en un proyecto del certamen, ¿no?

### ISSUE THREAD

**Issue by JJ** [computation-hs/comp-models#20]
:-)

**Comment by mroman42** [comment]
¡Sí!, mi intención es sólo presentarme con este proyecto. :-)

No sé si finalmente fui apuntado a M42/granasatClient como participante, pero ya avisé al equipo de que me iba a presentar con otro proyecto y de que no creía que fuera útil presentar un proyecto ya terminado. Como explico en M42/granasatClient#2, ese otro proyecto está acabado. Ni yo, ni creo que nadie, va a seguir aportando a él.

Así que yo debería estar apuntado sólo en este proyecto. Disculpas por la confusión.

**Comment by mroman42** [comment]
Cierro por aquí la issue. El problema está en GranaSAT, puede tratarse en M42/granasatClient.
Un saludo.

**Comment by JJ** [comment]
Justo, ese era.
